name: Reusable Kafka Tests

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Kafka repository name'
        required: false
        type: string
        default: 'Netcracker/qubership-kafka'
      service_branch:
        required: false
        type: string
        default: 'main'
      pipeline_branch:
        description: 'Test pipeline branch name'
        type: string
        required: true
        default: 'main'
      runner_type:
        description: 'Runner type (self-hosted or ubuntu-latest)'
        type: string
        required: false
        default: 'ubuntu-latest'
      service_versions_json:
        description: 'Kafka image versions as JSON'
        type: string
        required: false
        default: |
          [
            "qubership-docker-kafka-3",
            "qubership-docker-kafka-4"
          ]
      scope:
        description: 'Kafka Test Scope: pr or nightly'
        type: string
        required: false
        default: pr

  workflow_call:
    inputs:
      repository_name:
        description: 'Kafka repository name'
        required: false
        type: string
        default: 'Netcracker/qubership-kafka'
      service_branch:
        required: false
        type: string
      pipeline_branch:
        description: 'Test pipeline branch name'
        type: string
        required: true
      runner_type:
        description: 'Runner type (self-hosted or ubuntu-latest)'
        type: string
        required: false
        default: 'ubuntu-latest'
      service_versions_json:
        description: 'Kafka image versions as JSON'
        type: string
        required: false
        default: |
          [
            "qubership-docker-kafka-3",
            "qubership-docker-kafka-4"
          ]
      scope:
        description: 'Kafka Test Scope: pr or nightly'
        type: string
        required: false
        default: pr
    secrets:
      AWS_S3_ACCESS_KEY_ID:
        required: true
      AWS_S3_ACCESS_KEY_SECRET:
        required: true

jobs:
  prepare:
    runs-on: ${{ inputs.runner_type }}
    outputs:
      versions: ${{ steps.process-versions.outputs.versions }}
      previous_version: ${{ steps.process-versions.outputs.previous_version }}
      matrix: ${{ steps.process-versions.outputs.matrix }}
      service_images: ${{ steps.parse-matrix.outputs.service_images }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.service_branch }}'
          repository: '${{ inputs.repository_name }}'
          path: 'qubership-kafka'

      - name: Checkout pipeline
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.pipeline_branch }}'
          repository: 'netcracker/qubership-test-pipelines'
          path: 'qubership-test-pipelines'

      - name: Get latest tag
        id: get-latest-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(gh api repos/${{ inputs.repository_name }}/releases/latest --jq '.tag_name')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Latest tag: $LATEST_TAG"

      - name: Process latest tag and matrix generation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: process-versions
        working-directory: "${{ github.workspace }}/qubership-test-pipelines"
        run: |
          chmod +x ./scripts/matrix.sh
          if [[ "${{ inputs.scope }}" == "nightly" ]]; then
            CONFIG_FILE="./workflow-config/kafka_nightly.yaml"
          elif [[ "${{ inputs.scope }}" == "pr" ]]; then
            CONFIG_FILE="./workflow-config/kafka.yaml"
          else
            echo "::error::Invalid scope parameter '${{ inputs.scope }}'. Must be 'pr' or 'nightly'."
            exit 1
          fi
          ./scripts/matrix.sh "${{ steps.get-latest-tag.outputs.latest_tag }}" "$CONFIG_FILE" "${{ inputs.service_branch }}"
      - name: Parse JSON into matrix
        id: parse-matrix
        run: |
          IMAGES=$(echo '${{ inputs.service_versions_json }}' | jq -c '.')
          echo "Kafka Images: $IMAGES"
          echo "service_images=$IMAGES" >> $GITHUB_OUTPUT

  Kafka-Test-Cases:
    runs-on: ${{ inputs.runner_type }}
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.prepare.outputs.matrix) }}
        service_image: ${{ fromJson(needs.prepare.outputs.service_images) }}
    name: "${{ matrix.service_image }} | ${{ matrix.test.name }}"
    env:
      kfk_namespace: kafka
      kfk_max_attempts: 60
      kfk_timeout: '10s'
      kfk_max_attempts_for_provisioner: 100
      kfk_timeout_for_provisioner: '10s'
      kfk_path_to_chart: 'operator/charts/helm/kafka'
      kfk_srvc_namespace: kafka
      kfk_srvc_max_attempts: 100
      kfk_srvc_timeout: '10s'
      kfk_srvc_max_attempts_for_provisioner: 120
      kfk_srvc_timeout_for_provisioner: '10s'
      kfk_srvc_path_to_chart: 'operator/charts/helm/kafka-service'
    steps:
      # == 01 Start ======= Common pre-steps for all tests =======
      - name: "Print job parameters"
        run: |
          echo "======== Job parameters ======="
          echo "${{ toJson(matrix.test) }}"
      - name: Checkout pipeline
        uses: actions/checkout@v4
        with:
          ref: '${{ inputs.pipeline_branch }}'
          repository: 'netcracker/qubership-test-pipelines'
          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
      # == 01 End ======= Common pre-steps for all tests =======

      # == Start TLS certs addition if needed =======
      - name: TLS setup
        # language=bash
        if: matrix.test.tls == true
        run: |
          echo "::group::Install cert-manager"
          helm repo add jetstack https://charts.jetstack.io --force-update
          helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager \
            --create-namespace --version v1.16.3 --set prometheus.enabled=true   --set crds.enabled=true
          echo "::endgroup::"
          echo "::group::Create cert-manager entities"
          kubectl apply -f qubership-test-pipelines/resources/test-issuer.yaml
          sleep 10s
          kubectl apply -f qubership-test-pipelines/resources/test-certificate.yaml
          sleep 10s
          kubectl apply -f qubership-test-pipelines/resources/test-clusterissuer.yaml
          echo "::endgroup::"
          echo "::group::Get cert-manager resources"
          kubectl get pods -n cert-manager
          kubectl get secrets -n cert-manager
          kubectl get certificates -A
          echo "::endgroup::"
          echo "::group:: Get clusterissuer"
          kubectl get clusterissuer
          kubectl get clusterissuer test-clusterissuer -o yaml
          echo "::endgroup::"
      # == End TLS certs addition if needed =======

       # == Start Monitoring installation tests =======
      - name: Install Monitoring [${{ matrix.test.install_version }}]
        if: matrix.test.monitoring == true
        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
        id: monitoring_install
        with:
          path_to_template: 'templates/monitoring/vm_without_tests.yml'
          service_branch: 'main'
          service_name: 'monitoring'
          repository_name: 'Netcracker/qubership-monitoring-operator'
          path_to_chart: 'charts/qubership-monitoring-operator'
          namespace: 'monitoring'
          restricted: 'false'

      - name: Verify Monitoring installation
        uses: ./qubership-test-pipelines/actions/shared/verify_installation
        if: matrix.test.monitoring == true
        with:
          namespace: monitoring
          service_branch: 'main'
          test_completion_max_retries: 40
          test_completion_retry_interval: '10s'
          service_ready_max_retries: 80
          service_ready_retry_interval: '10s'
          monitoring_pipeline: 'true'
          repository_name: 'Netcracker/qubership-monitoring-operator'

      - name: Collect Diagnostics Monitoring installation
        if: ${{ !cancelled() && steps.monitoring_install.conclusion != 'skipped' }}
        uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
        with:
          namespace: 'monitoring'
          artifact_name: Install_Monitoring_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}
          service_branch: 'main'
      # == End Monitoring installation tests =======

      # == Start Zookeeper installation tests =======
      - name: Print install deployment parameters
        if: matrix.test.zookeeper == true
        run: cat qubership-test-pipelines/${{ matrix.test.zookeeper_template }}

      - name: Clean Install Zookeeper [LATEST]
        if: matrix.test.zookeeper == true
        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
        id: zoo_install
        with:
          path_to_template: '${{ matrix.test.zookeeper_template }}'
          service_branch: 'main'
          service_name: 'zookeeper-service'
          repository_name: 'Netcracker/qubership-zookeeper'
          path_to_chart: 'operator/charts/helm/zookeeper-service'
          namespace: 'zookeeper'

      - name: Verify Zookeeper installation
        if: matrix.test.zookeeper == true
        uses: ./qubership-test-pipelines/actions/shared/verify_installation
        with:
          service_branch: 'main'
          namespace: zookeeper
          test_completion_max_retries: 40
          test_completion_retry_interval: '10s'
          service_ready_max_retries: 80
          service_ready_retry_interval: '10s'
          repository_name: 'Netcracker/qubership-zookeeper'

      - name: Collect Diagnostics Zookeeper installation
        if: ${{ !cancelled() && steps.zoo_install.conclusion != 'skipped' }}
        uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
        with:
          namespace: zookeeper
          artifact_name: Install_Zookeeper_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}
          service_branch: 'main'
      # == End Zookeeper installation tests =======

      # == Start update YAML secrets if needed =======
      - name: Update YAML secrets
        if: matrix.test.storage == 's3'
        # language=bash
        run: |
          python qubership-test-pipelines/scripts/update_yaml.py \
            --file='qubership-test-pipelines/${{ matrix.test.kafka_template }}' \
            --path='global/secrets/backupDaemon/s3/keyId' \
            --value='${{secrets.AWS_S3_ACCESS_KEY_ID}}' \
          && python qubership-test-pipelines/scripts/update_yaml.py \
            --file='qubership-test-pipelines/${{ matrix.test.kafka_service_template }}' \
            --path='global/secrets/backupDaemon/s3/keySecret' \
            --value='${{secrets.AWS_S3_ACCESS_KEY_SECRET}}'
      # == End update YAML secrets if needed =======

      # == Start kafka installation tests =======
      - name: Print install deployment parameters
        run: cat qubership-test-pipelines/${{ matrix.test.kafka_template }}

      - name: Clean Install Kafka [${{ matrix.test.kafka_install_version }}]
        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
        id: kafka_core_install
        with:
          path_to_template: '${{ matrix.test.kafka_template }}'
          service_branch: '${{ matrix.test.kafka_install_version }}'
          service_name: 'kafka'
          repository_name: ${{ inputs.repository_name }}
          path_to_chart: '${{ env.kfk_path_to_chart}}'
          namespace: ${{ env.kfk_namespace }}
          image_replacement: ${{ matrix.service_image }}
          test_tags: '${{ matrix.test.test_tags }}'

      - name: Get Installed Kafka CRD name
        uses: ./qubership-test-pipelines/actions/shared/get_crds
        id: install_kafka_get_crds
        with:
          crd_location: '${{ inputs.repository_name }}/${{ env.kfk_path_to_chart}}/crds'

      - name: Verify Kafka installation
        uses: ./qubership-test-pipelines/actions/shared/verify_installation
        with:
          service_branch: '${{ matrix.test.install_version }}'
          check_tests: true
          namespace: ${{ env.kfk_namespace }}
          test_completion_max_retries: ${{ env.kfk_max_attempts }}
          test_completion_retry_interval: ${{ env.kfk_timeout }}
          service_ready_max_retries: ${{ env.kfk_max_attempts_for_provisioner }}
          service_ready_retry_interval: ${{ env.kfk_timeout_for_provisioner }}
          crd_list: ${{ steps.install_kafka_get_crds.outputs.crd_names }}

      - name: Collect Diagnostics Kafka Core installation
        if: ${{ !cancelled() && steps.kafka_core_install.conclusion != 'skipped' }}
        uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
        with:
          namespace: ${{ env.kfk_namespace }}
          artifact_name: Install_Kafka_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}
          service_branch: '${{ matrix.test.install_version }}'
      # == End kafka installation tests =======

      - name: Get Kafka secrets
        if: matrix.test.tls == true
        run: |
          kubectl get secrets -n kafka
          kubectl get secret kafka-tls-secret -n kafka -o yaml

      # == Start kafka service installation tests =======
      - name: Clean Install Kafka Service [${{ matrix.test.kafka_install_version }}]
        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
        id: kafka_service_install
        with:
          path_to_template: '${{ matrix.test.kafka_service_template }}'
          service_branch: '${{ matrix.test.kafka_install_version }}'
          service_name: 'kafka-service'
          repository_name: ${{ inputs.repository_name }}
          path_to_chart: '${{ env.kfk_srvc_path_to_chart }}'
          namespace: ${{ env.kfk_srvc_namespace }}
          test_tags: '${{ matrix.test.test_tags }}'

      - name: Get Installed Kafka-Service CRD name
        uses: ./qubership-test-pipelines/actions/shared/get_crds
        id: install_kafka_service_get_crds
        with:
          crd_location: '${{ inputs.repository_name }}/${{ env.kfk_srvc_path_to_chart}}/crds'

      - name: Verify Kafka Service installation
        uses: ./qubership-test-pipelines/actions/shared/verify_installation
        with:
          service_branch: '${{ matrix.test.install_version }}'
          check_tests: true
          namespace: ${{ env.kfk_srvc_namespace }}
          test_completion_max_retries: ${{ env.kfk_srvc_max_attempts }}
          test_completion_retry_interval: ${{ env.kfk_srvc_timeout }}
          service_ready_max_retries: ${{ env.kfk_srvc_max_attempts_for_provisioner }}
          service_ready_retry_interval: ${{ env.kfk_srvc_timeout_for_provisioner }}
          crd_list: ${{ steps.install_kafka_service_get_crds.outputs.crd_names }}

      - name: Collect Diagnostics Kafka Service installation
        if: ${{ !cancelled() && steps.kafka_service_install.conclusion != 'skipped' }}
        uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
        with:
          namespace: ${{ env.kfk_srvc_namespace }}
          artifact_name: Install_Kafka_Service_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}
          service_branch: '${{ matrix.test.install_version }}'
      # == End kafka service installation tests =======

      # == Start kafka upgrade tests =======
      - name: Print upgrade deployment parameters
        run: cat qubership-test-pipelines/${{ matrix.test.kafka_upgrade_template }}
        if: matrix.test.sequence == 'upgrade'

      - name: Upgrade Kafka to [${{ matrix.test.kafka_upgrade_version }}]
        if: matrix.test.sequence == 'upgrade'
        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
        id: kafka_core_upgrade
        with:
          path_to_template: '${{ matrix.test.kafka_upgrade_template }}'
          service_branch: '${{ matrix.test.kafka_upgrade_version }}'
          service_name: 'kafka'
          repository_name: ${{ inputs.repository_name }}
          path_to_chart: '${{ env.kfk_path_to_chart}}'
          namespace: ${{ env.kfk_namespace }}
          deploy_mode: upgrade
          image_replacement: ${{ matrix.service_image }}
          test_tags: '${{ matrix.test.test_tags }}'

      - name: Get Upgraded Kafka CRD name
        if: matrix.test.sequence == 'upgrade'
        uses: ./qubership-test-pipelines/actions/shared/get_crds
        id: upgrade_kafka_get_crds
        with:
          crd_location: '${{ inputs.repository_name }}/${{ env.kfk_path_to_chart}}/crds'

      - name: Sleep 1m after upgrade
        if: matrix.test.sequence == 'upgrade'
        run: sleep 1m

      - name: Verify Kafka upgrade
        if: matrix.test.sequence == 'upgrade'
        uses: ./qubership-test-pipelines/actions/shared/verify_installation
        with:
          service_branch: '${{ matrix.test.kafka_upgrade_version }}'
          check_tests: true
          namespace: ${{ env.kfk_namespace }}
          test_completion_max_retries: ${{ env.kfk_max_attempts }}
          test_completion_retry_interval: ${{ env.kfk_timeout }}
          service_ready_max_retries: ${{ env.kfk_max_attempts_for_provisioner }}
          service_ready_retry_interval: ${{ env.kfk_timeout_for_provisioner }}
          crd_list: ${{ steps.upgrade_kafka_get_crds.outputs.crd_names }}

      - name: Collect Diagnostics Kafka Core upgrade
        if: ${{ !cancelled() && steps.kafka_core_upgrade.conclusion != 'skipped' }}
        uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
        with:
          namespace: ${{ env.kfk_namespace }}
          artifact_name: Upgrade_Kafka_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}
          service_branch: '${{ matrix.test.kafka_upgrade_version }}'

      - name: Upgrade Kafka Service to [${{ matrix.test.kafka_upgrade_version }}]
        if: matrix.test.sequence == 'upgrade'
        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
        id: kafka_service_upgrade
        with:
          path_to_template: '${{ matrix.test.kafka_service_upgrade_template }}'
          service_branch: '${{ inputs.service_branch }}'
          service_name: 'kafka-service'
          repository_name: ${{ inputs.repository_name }}
          path_to_chart: '${{ env.kfk_srvc_path_to_chart }}'
          namespace: ${{ env.kfk_srvc_namespace }}
          deploy_mode: upgrade
          test_tags: '${{ matrix.test.test_tags }}'

      - name: Get Upgraded Kafka CRD name
        if: matrix.test.sequence == 'upgrade'
        uses: ./qubership-test-pipelines/actions/shared/get_crds
        id: upgrade_kafka_service_get_crds
        with:
          crd_location: '${{ inputs.repository_name }}/${{ env.kfk_srvc_path_to_chart}}/crds'

      - name: Sleep 1m after upgrade
        if: matrix.test.sequence == 'upgrade'
        run: sleep 1m

      - name: Verify Kafka Service upgrade
        if: matrix.test.sequence == 'upgrade'
        uses: ./qubership-test-pipelines/actions/shared/verify_installation
        with:
          service_branch: '${{ matrix.test.install_version }}'
          check_tests: true
          namespace: ${{ env.kfk_srvc_namespace }}
          test_completion_max_retries: ${{ env.kfk_srvc_max_attempts }}
          test_completion_retry_interval: ${{ env.kfk_srvc_timeout }}
          service_ready_max_retries: ${{ env.kfk_srvc_max_attempts_for_provisioner }}
          service_ready_retry_interval: ${{ env.kfk_srvc_timeout_for_provisioner }}
          crd_list: ${{ steps.upgrade_kafka_service_get_crds.outputs.crd_names }}

      - name: Collect Diagnostics Core installation
        if: ${{ !cancelled() && steps.kafka_service_upgrade.conclusion != 'skipped' }}
        uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
        with:
          namespace: ${{ env.kfk_srvc_namespace }}
          artifact_name: Upgrade_Kafka_Service_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}
          service_branch: '${{ matrix.test.install_version }}'
      # == End kafka upgrade tests =======

      # == Start kafka migrate tests =======
      # - name: Migrate Kafka to Kraft scheme
      #   if: matrix.test.sequence == 'migrate'
      #   uses: ./qubership-test-pipelines/actions/shared/helm_deploy
      #   id: kafka_migrate
      #   with:
      #     path_to_template: '${{ matrix.test.kafka_migrate_template }}'
      #     service_branch: '${{ matrix.test.kafka_migrate_version }}'
      #     service_name: 'kafka'
      #     repository_name: ${{ inputs.repository_name }}
      #     path_to_chart: 'operator/charts/helm/kafka'
      #     namespace: ${{ env.kfk_namespace }}
      #     deploy_mode: upgrade
      #     test_tags: '${{ matrix.test.test_tags }}'

      # - name: Sleep 1m after migration
      #   if: matrix.test.sequence == 'migrate'
      #   run: sleep 1m

      # - name: Verify Kafka migration
      #   if: matrix.test.sequence == 'migrate'
      #   uses: ./qubership-test-pipelines/actions/shared/verify_installation
      #   with:
      #     check_tests: true
      #     namespace: ${{ env.kfk_namespace }}
      #     test_completion_max_retries: ${{ env.kfk_max_attempts }}
      #     test_completion_retry_interval: ${{ env.kfk_timeout }}
      #     service_ready_max_retries: ${{ env.kfk_max_attempts_for_provisioner }}
      #     service_ready_retry_interval: ${{ env.kfk_timeout_for_provisioner }}
      #     crd_list: ${{ env.kfk_cr_name }}

      # - name: Collect Diagnostics Kafka Migration
      #   if: ${{ !cancelled() && steps.kafka_migrate.conclusion != 'skipped' }}
      #   uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
      #   with:
      #     namespace: ${{ env.kfk_namespace }}
      #     artifact_name: Upgrade_Kafka_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}

      # - name: Upgrade Kafka to [${{ matrix.test.kafka_upgrade_version }}]
      #   if: matrix.test.sequence == 'migrate'
      #   uses: ./qubership-test-pipelines/actions/shared/helm_deploy
      #   id: kafka_core_upgrade_migrate
      #   with:
      #     path_to_template: '${{ matrix.test.kafka_upgrade_template }}'
      #     service_branch: '${{ matrix.test.kafka_upgrade_version }}'
      #     service_name: 'kafka'
      #     repository_name: ${{ inputs.repository_name }}
      #     path_to_chart: 'operator/charts/helm/kafka'
      #     namespace: ${{ env.kfk_namespace }}
      #     deploy_mode: upgrade
      #     test_tags: '${{ matrix.test.test_tags }}'

      # - name: Sleep 1m after upgrade
      #   if: matrix.test.sequence == 'migrate'
      #   run: sleep 1m

      # - name: Verify Kafka upgrade
      #   if: matrix.test.sequence == 'migrate'
      #   uses: ./qubership-test-pipelines/actions/shared/verify_installation
      #   with:
      #     namespace: ${{ env.kfk_namespace }}
      #     test_completion_max_retries: ${{ env.kfk_max_attempts }}
      #     test_completion_retry_interval: ${{ env.kfk_timeout }}
      #     service_ready_max_retries: ${{ env.kfk_max_attempts_for_provisioner }}
      #     service_ready_retry_interval: ${{ env.kfk_timeout_for_provisioner }}
      #     crd_list: ${{ env.kfk_cr_name }}
      #     check_tests: true

      # - name: Collect Diagnostics Kafka Migration
      #   if: ${{ !cancelled() && steps.kafka_core_upgrade_migrate.conclusion != 'skipped' }}
      #   uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
      #   with:
      #     namespace: ${{ env.kfk_namespace }}
      #     artifact_name: Upgrade_Kafka_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}

      # - name: Upgrade Kafka Service to [${{ matrix.test.kafka_upgrade_version }}]
      #   if: matrix.test.sequence == 'migrate'
      #   uses: ./qubership-test-pipelines/actions/shared/helm_deploy
      #   id: kafka_service_upgrade_migrate
      #   with:
      #     path_to_template: '${{ matrix.test.kafka_service_migrate_template }}'
      #     service_branch: '${{ inputs.service_branch }}'
      #     service_name: 'kafka-service'
      #     repository_name: ${{ inputs.repository_name }}
      #     path_to_chart: 'operator/charts/helm/kafka-service'
      #     namespace: ${{ env.kfk_srvc_namespace }}
      #     deploy_mode: upgrade
      #     test_tags: '${{ matrix.test.test_tags }}'

      # - name: Sleep 1m after upgrade
      #   if: matrix.test.sequence == 'migrate'
      #   run: sleep 1m

      # - name: Verify Kafka Service upgrade
      #   if: matrix.test.sequence == 'migrate'
      #   uses: ./qubership-test-pipelines/actions/shared/verify_installation
      #   with:
      #     namespace: ${{ env.kfk_srvc_namespace }}
      #     test_completion_max_retries: ${{ env.kfk_srvc_max_attempts }}
      #     test_completion_retry_interval: ${{ env.kfk_srvc_timeout }}
      #     service_ready_max_retries: ${{ env.kfk_srvc_max_attempts_for_provisioner }}
      #     service_ready_retry_interval: ${{ env.kfk_srvc_timeout_for_provisioner }}
      #     crd_list: ${{ env.kfk_srvc_cr_name }}
      #     check_tests: true

      # - name: Verify Kafka Service upgrade
      #   if: matrix.test.sequence == 'migrate'
      #   uses: ./qubership-test-pipelines/actions/shared/verify_installation
      #   with:
      #     namespace: ${{ env.kfk_srvc_namespace }}
      #     test_completion_max_retries: ${{ env.kfk_srvc_max_attempts }}
      #     test_completion_retry_interval: ${{ env.kfk_srvc_timeout }}
      #     service_ready_max_retries: ${{ env.kfk_srvc_max_attempts_for_provisioner }}
      #     service_ready_retry_interval: ${{ env.kfk_srvc_timeout_for_provisioner }}
      #     crd_list: ${{ env.kfk_srvc_cr_name }}
      #     check_tests: true

      # - name: Collect Diagnostics Kafka Migration
      #   if: ${{ !cancelled() && steps.kafka_service_upgrade_migrate.conclusion != 'skipped' }}
      #   uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
      #   with:
      #     namespace: ${{ env.kfk_namespace }}
      #     artifact_name: Upgrade_Kafka_Service_${{ matrix.service_image }}_${{ matrix.test.artifact_name }}
      # == End kafka migrate tests =======

  final-status-check:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [Kafka-Test-Cases]
    steps:
      - name: Checkout pipeline
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.pipeline_branch }}'
          repository: 'netcracker/qubership-test-pipelines'
          path: 'qubership-test-pipelines'
      - name: Check job status
        uses: ./qubership-test-pipelines/actions/shared/check_job_status
        with:
          job_result: ${{ needs.Kafka-Test-Cases.result }}
