name: Reusable Monitoring Tests

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Repository with Monitoring service'
        required: false
        type: string
        default: 'Netcracker/qubership-monitoring-operator'
      service_branch:
        description: 'Branch of qubership-monitoring-operator repository'
        required: false
        type: string
        default: 'main'
      pipeline_branch:
        description: 'Branch of qubership-test-pipelines repository'
        type: string
        required: true
        default: 'main'
      runner_type:
        description: 'Runner type (self-hosted or ubuntu-latest)'
        type: string
        required: false
        default: 'ubuntu-latest'
      kind-layout:
        description: 'Kind cluster layout (single-node or multi-node)'
        type: string
        required: false
        default: 'multi-node'
  workflow_call:
    inputs:
      repository_name:
        description: 'Repository with Monitoring service'
        required: false
        type: string
        default: 'Netcracker/qubership-monitoring-operator'
      service_branch:
        description: 'Branch of qubership-monitoring-operator repository'
        required: false
        type: string
        default: 'main'
      pipeline_branch:
        description: 'Branch of qubership-test-pipelines repository'
        type: string
        required: true
        default: 'main'
      runner_type:
        description: 'Runner type (self-hosted or ubuntu-latest)'
        type: string
        required: false
        default: 'ubuntu-latest'
      kind-layout:
        description: 'Kind cluster layout (single-node or multi-node)'
        type: string
        required: false
        default: 'multi-node'

jobs:
  prepare:
    runs-on: ${{ inputs.runner_type }}
    outputs:
      versions: ${{ steps.process-versions.outputs.versions }}
      matrix: ${{ steps.process-versions.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: '${{ inputs.service_branch }}'
          repository: '${{ inputs.repository_name }}'
          path: 'qubership-monitoring-operator'

      - name: Checkout pipeline
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.pipeline_branch }}'
          repository: '${{ github.repository_owner }}/qubership-test-pipelines'
          path: 'qubership-test-pipelines'

      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "latest_tag=main" >> $GITHUB_OUTPUT

      - name: Process versions file and matrix generation
        id: process-versions
        working-directory: "${{ github.workspace }}/qubership-test-pipelines"
        run: |
          chmod +x ./scripts/matrix.sh
          ./scripts/matrix.sh "${{ steps.get-latest-tag.outputs.latest_tag }}" ./workflow-config/monitoring.yaml "${{ inputs.service_branch }}"

  Monitoring-Test-Cases:
    needs: prepare
    runs-on: ${{ inputs.runner_type }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.prepare.outputs.matrix) }}
    name: ${{ matrix.test.name }}
    env:
      path_to_chart: 'charts/qubership-monitoring-operator'
      test_completion_max_retries: 100
      test_completion_retry_interval: '5s'
      service_ready_max_retries: 100
      service_ready_retry_interval: '5s'
    steps:
      # == 01 Start ======= Common pre-steps for all tests =======
      - name: "Print job parameters"
        run: |
          echo "======== Job parameters ======="
          echo "${{ toJson(matrix.test) }}"

      - name: Checkout pipeline
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.pipeline_branch }}'
          repository: '${{ github.repository_owner }}/qubership-test-pipelines'
          path: 'qubership-test-pipelines'

      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
        with:
          kind-layout: '${{ inputs.kind-layout }}'

      - name: Install Ingress Controller
        uses: ./qubership-test-pipelines/actions/shared/create_ingress
      # == 01 End ======= Common pre-steps for all tests =======

      # == 02 Start ======= Installation steps =======
      - name: Install Monitoring [${{ matrix.test.install_version }}]
        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
        id: monitoring_install
        with:
          path_to_template: '${{ matrix.test.template }}'
          service_branch: '${{ matrix.test.install_version }}'
          service_name: 'monitoring'
          repository_name: '${{ inputs.repository_name }}'
          path_to_chart: 'charts/qubership-monitoring-operator'
          namespace: 'monitoring'
          restricted: '${{ matrix.test.restricted }}'

      - name: Get Installed Monitoring CR name
        uses: ./qubership-test-pipelines/actions/shared/get_crds
        id: install_monitoring_get_crds
        with:
          crd_location: '${{ inputs.repository_name}}/${{ env.path_to_chart}}/crds'

      - name: Verify Monitoring installation
        uses: ./qubership-test-pipelines/actions/shared/verify_installation
        with:
          namespace: 'monitoring'
          service_branch: '${{ matrix.test.install_version }}'
          service_ready_max_retries: ${{ env.service_ready_max_retries }}
          service_ready_retry_interval: ${{ env.service_ready_retry_interval }}
          test_completion_max_retries: ${{ env.test_completion_max_retries }}
          test_completion_retry_interval: ${{ env.test_completion_retry_interval }}
          crd_list: ${{ steps.install_monitoring_get_crds.outputs.crd_names }}
          check_tests: true
          monitoring_pipeline: 'true'
          repository_name: '${{ inputs.repository_name }}'

      - name: Collect Diagnostics Monitoring installation
        if: ${{ !cancelled() && steps.monitoring_install.conclusion != 'skipped' }}
        uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
        with:
          namespace: 'monitoring'
          artifact_name: 'Installation_${{ matrix.test.artifact_name }}'
          service_branch: '${{ matrix.test.install_version }}'

      # == 02 End ======= Installation steps =======

      # == Start ======= Specific steps for upgrade tests =======
      - name: Upgrade Monitoring to [${{ matrix.test.upgrade_version }}]
        if: matrix.test.sequence == 'upgrade'
        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
        id: monitoring_upgrade
        with:
          path_to_template: '${{ matrix.test.upgrade_template }}'
          service_branch: '${{ matrix.test.upgrade_version }}'
          deploy_mode: 'upgrade'
          service_name: 'monitoring'
          repository_name: '${{ inputs.repository_name }}'
          path_to_chart: 'charts/qubership-monitoring-operator'
          namespace: 'monitoring'
          restricted: '${{ matrix.test.restricted }}'

      - name: Sleep 2m
        if: matrix.test.sequence == 'upgrade'
        run: sleep 2m

      - name: Verify Monitoring upgrade
        if: matrix.test.sequence == 'upgrade'
        uses: ./qubership-test-pipelines/actions/shared/verify_installation
        with:
          namespace: 'monitoring'
          service_ready_max_retries: ${{ env.service_ready_max_retries }}
          service_ready_retry_interval: ${{ env.service_ready_retry_interval }}
          test_completion_max_retries: ${{ env.test_completion_max_retries }}
          test_completion_retry_interval: ${{ env.test_completion_retry_interval }}
          service_branch: '${{ matrix.test.upgrade_version }}'
          check_tests: true
          monitoring_pipeline: 'true'
          repository_name: '${{ inputs.repository_name }}'

      - name: Collect Diagnostics Monitoring installation
        if: ${{ !cancelled() && steps.monitoring_upgrade.conclusion != 'skipped' }}
        uses: ./qubership-test-pipelines/actions/shared/collect_diag_info
        with:
          namespace: 'monitoring'
          artifact_name: 'Upgrade_${{ matrix.test.artifact_name }}'
          service_branch: '${{ matrix.test.upgrade_version }}'
      # == End ======= Specific steps for upgrade tests =======

  final-status-check:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [Monitoring-Test-Cases]
    steps:
      - name: Checkout pipeline
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.pipeline_branch }}'
          repository: 'netcracker/qubership-test-pipelines'
          path: 'qubership-test-pipelines'
      - name: Check job status
        uses: ./qubership-test-pipelines/actions/shared/check_job_status
        with:
          job_result: ${{ needs.Monitoring-Test-Cases.result }}
